totally revert changes

diff --git a/.github/workflows/discord-webhook.yml b/.github/workflows/discord-webhook.yml
--- a/.github/workflows/discord-webhook.yml
+++ b/.github/workflows/discord-webhook.yml
@@ -15,24 +15,21 @@ jobs:
       - name: Send Discord notification for PR
         if: github.event_name == 'pull_request'
         run: |
-             BODY=$'${{ github.event.pull_request.body }}'
-             # Escape backticks and parentheses in BODY to avoid breaking Discord formatting
-             # ESCAPED_BODY=$(echo "$BODY" | sed 's/`/\\`/g; s/(/\\(/g; s/)/\\)/g')
-             ESCAPED_BODY=$(echo "$BODY" | sed 's/`/\\`/g')
-             response=$(curl -s -w "\n%{http_code}" -H "Content-Type: application/json" \
-              -X POST \
-              -d "$(jq -n --arg title "${{ github.event.pull_request.title }}" \
-              --arg url "${{ github.event.pull_request.html_url }}" \
-              --arg body "$(echo $BODY | sed 's/`/\\`/g')" \
-              --arg branch "${{ github.event.pull_request.head.ref }}" \
-              '{"content": "📣 **New Pull Request**: [\($title)](\($url))\n\n📝 **Description**: \($body)\n\n🚀 **Branch**: \($branch)"}')" \
-              ${{ secrets.DISCORD_WEBHOOK_URL }})
-             echo "$response"
-             response_code=$(echo "$response" | tail -n1)
-             if [ "$response_code" -ne 204 ]; then
-              echo "Failed to send Discord notification"
-              exit 1
-             fi
+          BODY=$'${{ github.event.pull_request.body }}'
+          response=$(curl -s -w "\n%{http_code}" -H "Content-Type: application/json" \
+            -X POST \
+            -d "$(jq -n --arg title "${{ github.event.pull_request.title }}" \
+            --arg url "${{ github.event.pull_request.html_url }}" \
+            --arg body "$(echo $BODY | sed 's/`/\\`/g')" \
+            --arg branch "${{ github.event.pull_request.head.ref }}" \
+            '{"content": "📣 **New Pull Request**: [\($title)](\($url))\n\n📝 **Description**: \($body)\n\n🚀 **Branch**: \($branch)"}')" \
+            ${{ secrets.DISCORD_WEBHOOK_URL }})
+          echo "$response"
+          response_code=$(echo "$response" | tail -n1)
+          if [ "$response_code" -ne 204 ]; then
+            echo "Failed to send Discord notification"
+            exit 1
+          fi
 
       - name: Send Discord notification for Release
         if: github.event_name == 'release'
