ci: improve triggers and Discord webhook action (#138)
Improve triggers:
- Run nightly every day of the week
- Rerun "Validate PR Title" action when a commit is pushed

Fix discord webhook for complex PR descriptions and add http status code check to discord webhook action.

diff --git a/.github/workflows/discord-webhook.yml b/.github/workflows/discord-webhook.yml
--- a/.github/workflows/discord-webhook.yml
+++ b/.github/workflows/discord-webhook.yml
@@ -2,7 +2,7 @@ name: DISCORD-WEBHOOK
 
 on:
   pull_request:
-    types: [opened]
+    types: [opened, reopened]
   release:
     types: [published]
 
@@ -15,15 +15,37 @@ jobs:
       - name: Send Discord notification for PR
         if: github.event_name == 'pull_request'
         run: |
-          curl -H "Content-Type: application/json" \
-          -X POST \
-          -d "{\"content\": \"📣 **New Pull Request**: [${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }})\n\n📝 **Description**: ${{ github.event.pull_request.body }}\n\n🚀 **Branch**: ${{ github.event.pull_request.head.ref }}\"}" \
-          ${{ secrets.DISCORD_WEBHOOK_URL }}
+          BODY=$'${{ github.event.pull_request.body }}'
+          response=$(curl -s -w "\n%{http_code}" -H "Content-Type: application/json" \
+            -X POST \
+            -d "$(jq -n --arg title "${{ github.event.pull_request.title }}" \
+            --arg url "${{ github.event.pull_request.html_url }}" \
+            --arg body "$(echo $BODY | sed 's/`/\\`/g')" \
+            --arg branch "${{ github.event.pull_request.head.ref }}" \
+            '{"content": "📣 **New Pull Request**: [\($title)](\($url))\n\n📝 **Description**: \($body)\n\n🚀 **Branch**: \($branch)"}')" \
+            ${{ secrets.DISCORD_WEBHOOK_URL }})
+          echo "$response"
+          response_code=$(echo "$response" | tail -n1)
+          if [ "$response_code" -ne 204 ]; then
+            echo "Failed to send Discord notification"
+            exit 1
+          fi
 
       - name: Send Discord notification for Release
         if: github.event_name == 'release'
         run: |
-          curl -H "Content-Type: application/json" \
+          BODY=$'${{ github.event.release.body }}'
+          response=$(curl -s -w "%{http_code}" -H "Content-Type: application/json" \
           -X POST \
-          -d "{\"content\": \"🎉 **New Release**: [${{ github.event.release.name }}](${{ github.event.release.html_url }})\n\n📦 **Version**: ${{ github.event.release.tag_name }}\n\n📝 **Description**: ${{ github.event.release.body }}\"}" \
-          ${{ secrets.DISCORD_WEBHOOK_URL }}
+          -d "$(jq -n --arg title "${{ github.event.release.title }}" \
+            --arg url "${{ github.event.release.html_url }}" \
+            --arg body "$(echo $BODY | sed 's/`/\\`/g')" \
+            --arg tag "${{ github.event.release.tag_name }}" \
+            '{"content": "🎉 **New Release**: [\($title)](\($url))\n\n📦 **Version**: \($tag)\n\n📝 **Description**: \($body)"}')" \
+          ${{ secrets.DISCORD_WEBHOOK_URL }})
+          echo "$response"
+          response_code=$(echo "$response" | tail -n1)
+          if [ "$response_code" -ne 204 ]; then
+            echo "Failed to send Discord notification"
+            exit 1
+          fi
